version: '3.8'

services:
  web:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3

